---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04
    steps:
      - name: Creds check
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: $ {{ secrets.DOCKERHUB_USER }}
          password: $ {{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"