name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04
    steps:
      - name: Print environment variables
        run: printenv
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCK_USER }}
          password: ${{ secrets.DOCK_TOKEN }}
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py test"
      
      - name: Run Lint
        run: docker compose run --rm app sh -c "flake8"